name: Publicar paquete en GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publicar-paquete:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      # Configurar archivo .npmrc para publicar en GitHub Packages
      # La acci칩n setup-node crea un archivo .npmrc en el runner. 
      # Cuando usas el input scope en la acci칩n setup-node, el archivo .npmrc incluye el prefijo de 치mbito.
      # Usa como referencia el token de la variable de entorno NODE_AUTH_TOKEN (GITHUB_TOKEN en realidad)
      - name: Configurar .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          # Usuario u organizaci칩n propietaria del workflow
          scope: '@icebeam7'

      - name: Instalar dependencias usando versiones de package-lock.json
        run: npm ci
      - name: Publicar el paquete en GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
